### ISSUE TITLE
Scoop installation specific folders not mentioned in documentation

### ISSUE THREAD

**Issue by nomadamo** [mmatyas/pegasus-docs#29]
The documentation presently does not mention the scoop config folders. Most scoop users would likely already know where to look for the app folders as well including where to place themes, but I think it may be worth mentioning in the documentation.

Example:
``` Current
* Windows: C:\Users\[username]\AppData\Local\pegasus-frontend\themes\
```
Suggested addition:
```
* Windows (scoop): C:\Users\[username]\scoop\apps\pegasus\current\config\themes\
* Other OS scoop folders 
```

Secondly, the post-installation notes provided after installing pegasus-fe via scoop are inaccurate.

```
Application settings are stored in the "%LOCALAPPDATA%\pegasus-frontend" directory, or the "config" folder inside the app directory.
```

This would also be good to update to something like:
```
Application settings are stored in the "%HOMEPATH%\scoop\apps\pegasus\current\config\" folder.
```

**Comment by mmatyas** [comment]
Sorry for the late reply! Thanks for the suggestion, I've added the scoop directory to the list of all config directories here: https://pegasus-frontend.org/docs/user-guide/config-dirs/.

For the post-installation notes, this is a community maintained package, so you might wish to contact the [package maintainer](https://github.com/Zliced13) about that. I think the file you're looking for is [here](https://github.com/Calinou/scoop-games/blob/master/bucket/pegasus.json).

**Comment by nomadamo** [comment]
Will do, thank you!
